# Site
name: "Uclusion Blog"
title: "Uclusion Blog"
description: "Blog for all things Uclusion"
logo: 'assets/images/logo.svg'
favicon: 'assets/images/favicon.ico'
paginate: 12
#baseurl: ''
email: 'info@uclusion.com'
#google_analytics: 'UA-46278016-1'
#disqus: 'demowebsite'
#sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  ben:
    name: Ben Follis
    display_name: Ben Follis
    gravatar: dc0d720e454e1018afb28e5b5ec1b521
    email: bfollis@uclusion.com
    web: https://www.uclusion.com
    twitter: https://twitter.com/UclusionHQ
    description: "Co-Founder of Uclusion"
  david:
    name: David Israel
    display_name: David Israel
    gravatar: 3ec012bf6520242fca950e0c9be9fa43
    email: disrael@uclusion.com
    web: https://www.uclusion.com
    twitter: https://twitter.com/UclusionHQ
    description: "Co-Founder of Uclusion"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Other
markdown: kramdown
highlighter: rouge
